schema_version: 1

context:
  version: 20.1

package:
  name: r_clang_${{ target_platform }}
  version: ${{ version }}

build:
  number: 1
  skip: not win

requirements:
  run:
    - clang_${{ target_platform }}  ${{ version }}.*
    - clangxx_${{ target_platform }}  ${{ version }}.*

tests:
  - files:
      recipe:
        - test.cpp
        - test_cxx17.cpp
    script: run_test.bat
    requirements:
      run:
        - if: win
          then: 
            - m2-make
            - m2-filesystem
            - posix
        - r-base >=3.6
        - r-usethis

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Activation scripts for using Clang as a compiler in R packages
  description: |
    Use clang as an alternative compiler for R packages. Add this as a
    build requirement using the Jinja function `compiler('r_clang')`.


  homepage: https://github.com/conda-forge/r_clang_activation-feedstock

extra:
  feedstock-name: r_clang_activation
  recipe-maintainers:
    - conda-forge/r
    - xhochy
